# Capstone — mirrors your deployed research paper

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/aryan-0018/FlyRank-ML-W1/blob/main/work/notebooks/capstone.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [16]:
!git clone https://github.com/aryan-0018/FlyRank-ML-W1.git

fatal: destination path 'FlyRank-ML-W1' already exists and is not an empty directory.

In [17]:
from pathlib import Path

guide_path = Path("FlyRank-ML-W1/GUIDE.md")

print("GUIDE exists:", guide_path.exists())

GUIDE exists: True

In [18]:
print(Path("FlyRank-ML-W1/GUIDE.md").read_text())

# GUIDE — how this repo works

Five minutes here saves you hours later. This is the operating manual: what every file is,
what you may edit, how the pieces connect, and where your own work goes.

## 1. The map

| Path | What it is | Your relationship to it |
|---|---|---|
| `README.md` | Front door: quickstart + safety summary | Read once |
| `GUIDE.md` | This file | Read once, revisit when unsure |
| `SETUP.md` | GitHub + Colab (Week 1) and Hugging Face access (Week 3) — with the silent pitfalls | Follow it at those two moments |
| `DATA_USE.md` | The data rules you agree to by working here | **Read before touching the data** |
| `LICENSE` | MIT — covers the **code** only; the data is governed by `DATA_USE.md` | Reference |
| `data/raw/content_refresh_anonymized.csv` | The one dataset that ships here: 30,000 pseudonymized pages × 44 columns | **Read-only.** Never add files under `data/` |
| `data/processed/` | Intermediate files the pipeline writes (created on first run; gitignored) | Leave alone — delete freely, it regenerates |
| `scripts/01…05` + `run_all.py` | The **reference pipeline**: prepare → baseline → train → evaluate → PDF | **Run it and copy from it — don't edit it.** It's the baseline you compare your work against, and reviewers expect to find it unchanged |
| `scripts/ml_utils.py` | Shared paths, helpers, and the feature lists | The one `scripts/` file you *may* edit — e.g. `MODEL_NUMERIC_FEATURES` to try a feature idea. Note any change in your report |
| `notebooks/01`, `notebooks/02` | Week 1–2 guided notebooks (Colab-ready) | Run top to bottom; do the "your turn" cells |
| `notebooks/03` | Weeks 3+: the **full warehouse release** via DuckDB + Hugging Face | The workflow your lane and capstone run on — aggregate in SQL, model in sklearn |
| `outputs/` | Pipeline results. Three **committed examples** show the target shape (`model_report.md`, `refresh_queue_sample.csv`, `charts/`); everything else regenerates | Regenerated files are gitignored — that's intentional (see FAQ) |
| `work/` | **Yours.** Lane experiments, capstone notebook, report | Everything you build lives here — start with `work/README.md` |
| `docs/data-dictionary.md` | All 44 columns: meaning, scale, gotchas | Keep open while you work |
| `docs/ml-intern-dataset-and-lane-guide.md` | Data safety, the lanes, the capstone workflow | Read in Week 1–2 |
| `docs/ml-core-foundation-framework.md` | The ML-as-a-system map behind the live sessions | Reference |
| `docs/intern-free-tooling-guide.md` | The zero-budget tool stack | Reference |
| `.github/workflows/smoke-test.yml` | CI: re-runs the whole pipeline and fails if any dataset CSV is committed | Keep it green |
| `.github/workflows/personalize.yml` | Runs once right after you create your copy: points every Colab badge at YOUR repo | Automatic — nothing to do |
| `requirements.txt` | pandas, numpy, scikit-learn, matplotlib, reportlab, duckdb, huggingface_hub | `pip install -r requirements.txt` |

## 2. How the pipeline fits together

```text
data/raw/content_refresh_anonymized.csv        (30,000 rows × 44 columns)
      │
      │  01_prepare_features.py    fill blanks, add engineered columns, define the label
      ▼
data/processed/refresh_feature_vector.csv      (52 columns)
      │
      │  02_baseline_score.py      transparent hand-rule score + reason codes
      ▼
data/processed/baseline_refresh_queue.csv
      │
      │  03_train_model.py         3 models, client-holdout split, metrics vs the baseline
      ▼
data/processed/model_predictions.csv  +  outputs/model_results.json
      │
      │  04_evaluate_and_export.py blend model + baseline → final ranked queue, charts, report
      ▼
outputs/refresh_queue.csv, outputs/model_report.md, outputs/charts/
      │
      │  05_build_pdf_report.py
      ▼
outputs/flyrank_refresh_model_results.pdf
```

`python scripts/run_all.py` runs all five stages in order (~1 minute).

**The label:** `is_declining_label = (trend_direction == "down")`. Because the label is
derived from `trend_direction`, neither `trend_direction` nor `trend_pct` may ever be a
model feature — notebook 02 shows you exactly what happens if you leak them in.

**The split:** `03_train_model.py` holds out ~20% of *clients* (not rows), so no client's
pages appear in both train and test. When you evaluate your own models, use the same idea.

## 3. Committed vs regenerated

Git deliberately ignores most of what the pipeline writes (`data/processed/`, `outputs/*.json`,
`outputs/refresh_queue.csv`, the PDF). Only three example outputs are committed so you can see
the target shape before running anything. If `git status` stays quiet after a pipeline run,
nothing is wrong — that's the design: **code and reports go in git, data and generated
artifacts don't.**

## 4. The working rhythm

| When | What you do | Where |
|---|---|---|
| Week 1 | Run the pipeline, make your first real discovery | `notebooks/01_first_look_and_discovery.ipynb` |
| Week 2 | Hand rule vs readable model, leakage lesson | `notebooks/02_your_first_readable_model.ipynb` |
| Weeks 3+ | Learn the full-release workflow (DuckDB over ~79M hosted rows), then your lane | `notebooks/03_working_with_the_full_release.ipynb`, then `work/` (copy pipeline pieces in, don't edit `scripts/`) |
| Capstone | Your `work/` folder **is** the deliverable: code, figures, and `capstone_report.md` | `work/` |

**Do I make my own notebook?** Weeks 1-3: no — run the three provided ones and do the "your
turn" cells (save copies to your repo). Capstone and lane work: **yes** — your own notebooks in
`work/notebooks/`, starting with the setup cell from section 5.

Weekly assignments, live events, and every "what done looks like" live on your **portal board** —
this repo is the technical foundation they all build on.

## 5. Build & submit flow

1. Make your own copy: **Use this template → Create a new repository** (public) on the repo
   page — that copy is your workspace, your submission, and your portfolio. (Prefer the
   terminal? `git clone` this repo and push it to an **empty** repo you own — no README tick,
   or the push is rejected.)
2. Share your repo URL as part of **Assignment 1** on the InternHQ board. That's the only thing
   you ever hand over during the track — nothing gets uploaded to the platform.
3. Build everything in `work/`. Keep `scripts/` pristine. **Every new notebook you create
   (weeks 3+) should start with one setup cell:**
   ```python
   %pip install -q duckdb huggingface_hub pandas scikit-learn matplotlib
   ```
   A fresh Colab/Jupyter kernel doesn't have `duckdb` until you install it in the notebook.
   And **never hardcode your Hugging Face token in a cell** — your repo is public. Use
   `getpass` or Colab's Secrets (🔑) panel; leaked tokens get auto-revoked, but don't test it.
4. Keep CI green: it re-runs the pipeline and **fails if any dataset CSV is committed** —
   your fork inherits that protection.
5. Submitting is simple: for every assignment you submit **your repo URL** on its card in your
   portal — and at the end you submit the capstone the same way, with your deployed paper's URL
   in `submission/paper_url.txt` inside the repo. That's the whole journey.

Working in Colab? *File → Save a copy in GitHub* after each session — opened from your
copy's badges, the dialog comes pre-filled (repo, path, branch), so saving is one OK. Also
*File → Save a copy in Drive* so the session doesn't evaporate. Badges acting up? *File →
Open notebook → GitHub tab* → your repo — see `SETUP.md`, Moment 1.

## 6. Working with an AI assistant

This repo ships its own **skill library** for AI coding assistants (Claude Code, Cursor, Codex,
ChatGPT — any of them). Start every task by telling your assistant:

> Read `skills/README.md`, then load the ONE skill this assignment names on its card.

The router in `skills/README.md` maps every task to its skill. Load one skill at a time — never
all of them (your assistant's memory is small, and stuffing it makes it worse, not better).
Using a chat-only assistant in the browser? Open the skill file on GitHub and paste its content
into your chat first. Repo-reading agents find the router automatically through `AGENTS.md` and
`CLAUDE.md` at the repo root.

## 7. FAQ — the questions everyone asks

**Git won't add my results / my CSV.**
By design — see section 3. Generated artifacts regenerate; datasets never enter git. Your
findings belong in your report and figures, not in committed data files.

**My numbers differ from the committed report.**
The baseline (Precision@50 = 0.240) reproduces exactly. The random-forest number is
**library-version sensitive**: 0.740 on the stack we ship, but roughly 0.68–0.74 across
older numpy/scikit-learn combinations — the picks at the 50th-place boundary shift.
The stable claim is the **~3x lift over the baseline**, not the third decimal. If you see
0.68-ish, your environment resolved older libraries; `pip install -r requirements.txt` in a
fresh venv gets you the shipped stack.

**"Raw input not found" when running the pipeline.**
The starter CSV was deleted or moved. Restore it:
`git checkout -- data/raw/content_refresh_anonymized.csv`

**How do I add or remove a model feature?**
Edit `MODEL_NUMERIC_FEATURES` / `MODEL_CATEGORICAL_FEATURES` in `scripts/ml_utils.py` and
re-run — or, for bigger experiments, copy `03_train_model.py` into `work/` and modify the
copy. Check `docs/data-dictionary.md` first so you don't leak the label.

**Can I put the mentor-provided warehouse release in this repo?**
No. It stays outside git entirely (CI fails any committed CSV anyway). Work with it locally
and commit only code, aggregates, and write-ups — see `DATA_USE.md`.

**How do I get starter fixes that ship after I made my copy?**
Template copies share no history with the shared repo, so fixes don't arrive on their own.
Pull them in when you want them:

```bash
git remote add upstream https://github.com/flyrank-bih/flyrank-ml-internship-starter
git fetch upstream
git merge upstream/main --allow-unrelated-histories
```

Badge lines will conflict (they were rewritten to point at YOUR copy) — resolve those by
keeping yours. Everything that matters for correctness is also announced on your portal
board, so syncing is optional, not required.

In [19]:
%pip install -q duckdb huggingface_hub pandas scikit-learn matplotlib

In [20]:
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

print("HF_TOKEN loaded:", HF_TOKEN is not None)

HF_TOKEN loaded: True

In [21]:
import os

os.environ["HF_TOKEN"] = HF_TOKEN

print("Hugging Face access token configured for this session.")

Hugging Face access token configured for this session.

In [22]:
import duckdb

con = duckdb.connect()

con.execute("""
CREATE SECRET (
    TYPE huggingface,
    TOKEN ?
)
""", [HF_TOKEN])

print("DuckDB connected successfully.")
print("Hugging Face access configured in DuckDB.")

DuckDB connected successfully.
Hugging Face access configured in DuckDB.

In [23]:
WAREHOUSE = "hf://datasets/FlyRank/internship-warehouse"
TABLE_PATH = f"{WAREHOUSE}/fact_content_daily_performance/**/*.parquet"

print("Warehouse path configured.")

Warehouse path configured.

In [24]:
schema = con.sql(f"""
DESCRIBE
SELECT *
FROM read_parquet(
    '{TABLE_PATH}',
    hive_partitioning=true
)
LIMIT 1
""")

display(schema.df())

                 column_name column_type null   key default extra
0                report_date        DATE  YES  None    None  None
1             client_hash_id     VARCHAR  YES  None    None  None
2            content_hash_id     VARCHAR  YES  None    None  None
3             client_has_gsc     BOOLEAN  YES  None    None  None
4             client_has_ga4     BOOLEAN  YES  None    None  None
5         gsc_data_available     BOOLEAN  YES  None    None  None
6         ga4_data_available     BOOLEAN  YES  None    None  None
7            gsc_impressions      BIGINT  YES  None    None  None
8                 gsc_clicks      BIGINT  YES  None    None  None
9           gsc_sum_position      BIGINT  YES  None    None  None
10          gsc_avg_position      DOUBLE  YES  None    None  None
11             ga4_pageviews      BIGINT  YES  None    None  None
12              ga4_sessions      BIGINT  YES  None    None  None
13                 ga4_users      BIGINT  YES  None    None  None
14      ga4_engaged_sessions      BIGINT  YES  None    None  None
15  ga4_total_engagement_sec      BIGINT  YES  None    None  None
16          sessions_organic      BIGINT  YES  None    None  None
17           sessions_direct      BIGINT  YES  None    None  None
18         sessions_referral      BIGINT  YES  None    None  None
19           sessions_social      BIGINT  YES  None    None  None
20             sessions_paid      BIGINT  YES  None    None  None
21               sessions_ai      BIGINT  YES  None    None  None
22                ai_chatgpt      BIGINT  YES  None    None  None
23             ai_perplexity      BIGINT  YES  None    None  None
24                 ai_gemini      BIGINT  YES  None    None  None
25                ai_copilot      BIGINT  YES  None    None  None
26                 ai_claude      BIGINT  YES  None    None  None
27                   ai_meta      BIGINT  YES  None    None  None
28                  ai_other      BIGINT  YES  None    None  None
29             scroll_events      BIGINT  YES  None    None  None
30                     month     VARCHAR  YES  None    None  None

In [25]:
date_check = con.sql(f"""
SELECT
    MIN(report_date) AS min_date,
    MAX(report_date) AS max_date,
    COUNT(*) AS row_count
FROM read_parquet(
    '{TABLE_PATH}',
    hive_partitioning=true
)
""")

display(date_check.df())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

    min_date   max_date  row_count
0 2025-01-27 2026-06-30   78835655

In [26]:
from pathlib import Path

print(Path("FlyRank-ML-W1/DATA_USE.md").read_text())

# Data Use & Public-Safety Rules

The one dataset that ships with this repo is:

```text
data/raw/content_refresh_anonymized.csv
```

It is a small, **anonymized** slice of FlyRank content-performance data — one row per
pseudonymized content item, with observed search/engagement metrics, content metadata,
age/freshness fields, and derived comparison windows.

## What has already been removed

The starter export contains **no**:

- client names
- domains
- URLs
- page titles
- keywords or raw search queries
- product-rule flags used as composite scores you should trust blindly

Only hashed `content_id` / `client_id` labels plus numeric and categorical metrics remain.

Rate columns (`ctr`, `engagement_rate`, `scroll_rate`, `ai_traffic_pct`, `trend_pct`) are
percentages on a 0–100 scale: `ctr = 0.76` means 0.76%, not 76%.

The hashed IDs are pseudonyms derived from FlyRank-internal database identifiers. They
contain no public information, but treat them as pseudonymous, not anonymous: use them
for grouping and joining only, never as model features, and never attempt to map them back.

## Your rules while working

1. **Do not add raw private client data** to this repo or any fork of it. If you need
   more data than the starter slice, request an approved release from your mentor —
   never export it yourself.
2. **Do not paste this data (or any client data) into third-party tools** — cloud AI
   assistants, free APIs, hosted notebooks — beyond what the approved release allows.
   Treat every external tool as third-party processing.
3. **Hashed IDs are for grouping/joining/validation only** — use them for grouped
   train/test splits, not as model features.
4. **Observable signals only.** The starter data ships observable search/engagement
   metrics and transparent derived buckets. FlyRank's product decision flags and scores
   (`health_score`, `needs_ctr_fix`, `is_quick_win`, …) are intentionally not included,
   so you build from observable evidence and never learn the product's own decision.
5. **Public outputs must use careful language** — *observed, measured, directional,
   decision-support*. Never claim you "predicted Google's algorithm" or proved causal
   refresh impact. Publish aggregates, charts, and pseudonymized IDs — never careless
   row-level dumps.

## When you publish your capstone

Your final repo is public. Before you push:

- confirm no raw client identifiers, URLs, or queries appear anywhere;
- confirm you did not commit a larger dataset than the anonymized starter slice;
- keep claims honest and decision-support framed.

CI fails any commit that includes a dataset or leaks client-identifying
patterns — this rule doubles as the public-safety discipline the internship teaches.

In [27]:
lane_guide = Path(
    "FlyRank-ML-W1/docs/ml-intern-dataset-and-lane-guide.md"
)

print(lane_guide.read_text())

# FlyRank ML Internship - Your Dataset and Lane Guide

Status: your guide for the Applied Search Intelligence track.

Read this together with:

- `docs/ml-core-foundation-framework.md` (ships in this repo — a deep reference, not week-one reading)
- `docs/intern-free-tooling-guide.md` (ships in this repo)
- the week-by-week curriculum on your portal board
- the data dictionary and manifest that ship inside the dataset release on Hugging Face

> This starter repo ships only the small anonymized starter dataset (`data/raw/content_refresh_anonymized.csv`).
> The much larger warehouse release lives on Hugging Face at
> [`FlyRank/internship-warehouse`](https://huggingface.co/datasets/FlyRank/internship-warehouse).
> It is gated, which means you click "request access" and accept the data-use terms first —
> approval is instant, so you can get it yourself whenever your lane needs it.

This guide shows you how to use the data without turning the internship into a fill-in-the-blank exercise. The goal is not to memorize FlyRank's existing rules. The goal is to understand the problem, look at the evidence, build a simple starting point, test a better method, check it honestly, and turn the result into a ranked list of safe recommendations.

## 0. Where These Numbers Come From

Every count and date in this guide was checked against the real data pipeline, not written from memory. The release itself was built, scrambled, and verified on FlyRank's side before it was published; the details of that build live in the dataset manifest that ships with the release on Hugging Face. You don't need any of that tooling — everything you need is already in this repo and on Hugging Face:

- the runnable starter pipeline (`scripts/01`–`05`, `ml_utils.py`, `run_all.py`);
- its verified committed outputs (`outputs/model_report.md`, `outputs/refresh_queue_sample.csv`, `outputs/charts/`); `outputs/model_results.json` is regenerated when you run the pipeline;
- the small anonymized starter dataset (`data/raw/content_refresh_anonymized.csv`).

One important rule about snapshots (a snapshot is a copy of the data frozen at one moment in time):

- For warehouse work, use the Hugging Face release. It is a fixed snapshot with the exact date windows written out below.
- Stick to this release for your internship work — it is the snapshot every number in this guide describes, so results built on it can be compared and rerun.
- You never need raw BigQuery credentials, raw client names, raw domains, raw URLs, raw private queries, or raw text. Everything sensitive was removed or scrambled before release.

## 1. The Core Idea

The whole track follows one workflow:

```text
research question -> safe data contract -> signal audit -> baseline score -> your chosen lane -> validation -> ranked action recommendations
```

Here is what those words mean, in order. A **research question** is the one question your project answers. A **data contract** is a short written promise about which data you will use and how. A **signal audit** is a check of whether the columns actually contain useful information. A **baseline** is the simplest possible method, built first, so you have something honest to beat. **Validation** is the test that proves your result is real and not an accident. **Ranked action recommendations** are the final output: a list of pages, ordered by which one someone should look at first.

The teaching method is:

```text
core idea first -> AI-assisted implementation second -> human judgment last
```

That means:

- Start with the content and search problem, not with a model.
- Use AI to draft code, ideas, checks, and explanations — but never let AI decide what is true. You check that yourself, against the data.
- Treat product scores and flags as useful background, not as the truth.
- Prefer simple methods you can explain, until something harder is clearly worth it.
- Tie every claim you make to something the data can actually prove.

Your deliverables along the way are notebooks, and they already have homes: pre-named skeleton notebooks live in `work/notebooks/` (for example `w01_research_question.ipynb` through `w07_action_playbook.ipynb`, plus `capstone.ipynb`). You fill those in — you do not create separate report files.

## 2. Which Data To Use

Your internship data is the warehouse release described below, plus the small runnable starter dataset that ships in this repo. Both contain **observable signals only** — real measurements of what happened, never the product's own decisions.

### About the Release

The warehouse release, and how to get it:

- Release: [`FlyRank/internship-warehouse`](https://huggingface.co/datasets/FlyRank/internship-warehouse) on Hugging Face. It is gated — request access, accept the data-use terms, and approval is instant. Notebook 03 shows the DuckDB workflow for reading it. Build id: `flyrank_pseudonymized_warehouse_release_v20260703`.
- Source: `central_data_warehouse`
- Export date: `2026-07-03`
- Freshness lag: the freshest 3 days were cut off on purpose, because the very newest rows are often incomplete — 3 days back from `2026-07-03` means daily time-series facts stop at `2026-06-30`
- Chunk size: 10,000 rows per CSV part
- How it was scrambled and verified: identifiers were pseudonymized (replaced with stable scrambled codes) and the release passed its checks before publishing — the full details are in the dataset manifest on Hugging Face.

> **Building features and iterating?** Develop against one middle month (e.g. `month=2026-03`) and run the full fact table only for your final pass — hitting the full table over and over can trip Hugging Face rate limits (HTTP 429 errors). Avoid the `_sample` table for experiments: it holds the LAST month of data, and if your label is about "what happens next", experimenting there means peeking at the future you're supposed to predict.

When you write about the data, use only the counts and date windows below — they match the release exactly.

### Which Lanes Are Ready, and With What Data

A **lane** is a project direction you can pick. Four lanes are predefined, and freestyle means bringing your own question (section 9 explains it).

| Lane | Type | Default dataset | Output |
|---|---|---|---|
| Ranking Signal Analysis | Core lane | warehouse release or starter dataset | Signal report and evidence-backed recommendations |
| Refresh / Content Opportunity Scoring | Core lane | starter playground plus warehouse support | Ranked review queue with scores, actions, and reason codes |
| Structured Content Archetype Clustering | Core lane | warehouse release or starter dataset | Cluster profiles and action mapping; do not call this semantic clustering |
| CTR / Engagement Opportunity Scoring | Core lane | warehouse release or starter dataset | Ranked opportunity score; position/volume adjusted |
| AI Referral Opportunity | Freestyle direction | warehouse daily facts (`sessions_ai`; starter dataset: `ai_sessions_90d` / `ai_traffic_pct`) | EDA/ranking only by default; positive examples are sparse |
| Growth / Recovery / Momentum Prediction | Freestyle direction | warehouse daily facts with time windows you build yourself | Future-window model with strict leakage audit |

### The Warehouse Tables

The warehouse release gives you **dimension tables** and **fact tables**. A dimension table describes things (one row per client, one row per content item). A fact table records events over time (one row per content item per day). You define your own joins, windows, labels, and leakage checks — that freedom is the point.

The release is hosted at
[`FlyRank/internship-warehouse`](https://huggingface.co/datasets/FlyRank/internship-warehouse)
(gated; Parquet files; see notebook 03). Ready-made example cuts for each lane live at
[`FlyRank/internship-lanes`](https://huggingface.co/datasets/FlyRank/internship-lanes). Build id:

```text
flyrank_pseudonymized_warehouse_release_v20260703
```

| Table | Rows | Grain | Main use |
|---|---:|---|---|
| `dim_clients` | 104 | one row per pseudonymized client | grouping, client-level checks, per-client history coverage (`gsc_data_start`, `ga4_data_start`) |
| `dim_content` | 519,606 | one row per pseudonymized content item | content metadata and joins |
| `fact_content_daily_performance` | 78,835,655 | daily x client x content | time-series features, trend labels, forward-window validation |
| `fact_content_query_90d` | 2,414,248 | client x content x query hash (fixed 90-day window) | query-mix features: diversity, concentration, rare/anonymized tail |

(**Grain** means "what one row stands for." Always know the grain before you touch a table.)

Use the warehouse data when you want the most freedom. The trade is that you must then write a stronger data contract, because you now control the joins, the windows, the labels, and the leakage risks yourself.

What went into the snapshot:

| Source object | Source rows | Clients | Content items | What it contributes |
|---|---:|---:|---:|---|
| `all_content_data` | 520,006 | 84 | 519,606 | Primary content dimension source |
| `daily_content_performance_v2` | 78,835,655 | 70 | 427,292 | Primary daily fact source (v2 full history), excluding the freshest 3 days |

The snapshot's date windows:

| Source/date field | Min date | Max date |
|---|---|---|
| `all_content_data.content_created_at` | 2024-10-16 | 2026-07-06 |
| `daily_content_performance_v2.report_date` | 2025-01-27 | 2026-06-30 |

The history is an **unbalanced panel** — a fancy way of saying that different clients have different amounts of history. The daily data starts 2025-01-27 at the earliest, and each client's history begins whenever their tracking started (9 of the 70 clients have 12+ months, which is enough for seasonality work). Rows from before a client's GA4 start contain search data only, with `ga4_data_available = FALSE`. So before you define any time window, check `dim_clients.gsc_data_start` and `ga4_data_start` — otherwise you may accidentally treat "no tracking yet" as "no traffic."

How dense each metric is inside the snapshot (not every row has every measurement):

| Metric presence | Rows |
|---|---:|
| daily fact rows | 78,835,655 |
| rows with GSC impressions | 28,970,051 |
| rows with GSC clicks | 3,112,607 |
| rows with GA4 sessions | 2,778,564 |
| rows with AI sessions | 30,177 |
| rows with scroll events | 600,821 |

What this table tells you:

- The search-performance and lifecycle lanes have the deepest data.
- The CTR and engagement lanes have enough direct signal, but you will still need minimum-volume filters (rules like "only look at pages with at least N impressions") to keep noise out.
- AI-referral analysis is possible, but AI-session rows are far thinner than search impressions — notice 30,177 versus 28,970,051.
- The daily table is huge because it is a fact table. Do not flatten it into one row per page without thinking; first choose your decision grain and your feature and target windows.

How the tables were assembled (one-paragraph version — the manifest has the rest):

- `dim_clients` combines every client that appears in the client, content, and daily performance sources.
- `dim_content` deduplicates content into one row per pseudonymized content item.
- `fact_content_daily_performance` cuts off the freshest 3 days: `report_date <= DATE_SUB(DATE('2026-07-03'), INTERVAL 3 DAY)` (so daily facts run through `2026-06-30`).
- Raw client names, domains, raw URLs, raw queries, raw keywords, content titles, and any files that could link scrambled ids back to real ones are not in the release.

Keys and joins (a **join** connects two tables through a shared id column):

| Table | Key |
|---|---|
| `dim_clients` | `client_hash_id` |
| `dim_content` | `content_hash_id` |
| `fact_content_daily_performance` | `report_date + client_hash_id + content_hash_id` |

Join rules:

- Join content facts to `dim_content` on `content_hash_id`.
- Join client-level facts to `dim_clients` on `client_hash_id`.
- Use `keyword_hash_id` and `url_hash_id` (on `dim_content`) for grouping, deduplication, leakage checks, and case analysis. Never try to work out what real keyword or URL a hash stands for.

## 3. Field Types

When you open a table, sort every column into one of these buckets before you model anything. This ten-minute habit prevents most of the painful mistakes later.

| Field type | Meaning | Example fields | Default use |
|---|---|---|---|
| Join keys | Scrambled ids that connect tables | `client_hash_id`, `content_hash_id`, `url_hash_id`, `keyword_hash_id` | Join and group only; the codes themselves mean nothing |
| Observed signals | Real measurements from search, analytics, or content metadata | impressions, clicks, position, CTR, sessions, scroll rate, word count, age | Good candidate features, as long as they were known before the decision point |
| Derived measurements | Numbers calculated from observed signals | `trend_pct`, age/freshness tiers, position tier | Usually fine, if calculated only from the feature window |
| Product context | Rule-outputs FlyRank's app computes (`health_score`, `priority_score`, `action_type`, refresh flags) — these are NOT shipped in your data | `health_score`, `priority_score`, `action_type`, `refresh_tier`, flags | Not in your dataset. If you ever rebuild one yourself, treat it as background or as a baseline to beat — never as a feature or a label for discovery |
| Target/proxy fields | The thing your model or analysis tries to predict or rank | future decline, recovery, top-K action priority, cluster membership | You must define these yourself, in your data contract |
| Raw-origin context | Columns that started life as real search queries, web addresses, titles, or client details | raw query/URL/title/client fields | These were scrambled before you got them, and the originals are never in your data. If your output ever shows something that looks like a real name or address, stop and remove it |

## 4. Observable Signals, Not Product Decisions

FlyRank's product computes rule-based decision flags and combined scores with hand-tuned SQL — things like `health_score`, `needs_ctr_fix`, `is_quick_win`, a `priority_score`, and an `action_type`. Those are how the live app decides which pages to surface.

Those product decisions are deliberately **not** in your data. Your data ships observable search and engagement signals, plus transparent derived buckets (tiers, `trend_direction`, `trend_pct`, ctr, rates) — and nothing else. This is on purpose, so you discover signal from evidence instead of accidentally copying the product's own answers.

Here is why this matters so much: if you feed the product's own decision into your model, the model just learns to copy that decision. The score looks great, but you discovered nothing — the answer was already in the input. That trap is called a **circular result**. So build only from observable signals (things that were true BEFORE anyone decided anything), and let your model find its own signal.

The strongest labels for supervised learning come from **future observed outcomes**, not from a current decision. Prefer labels like: traffic that later declined, a page that later recovered, CTR that later changed, or engagement that later changed — always measured after a clearly defined decision point. If you ever choose to rebuild a product flag and predict it, say so out loud in your write-up, and present it honestly as "can I reproduce the existing rule?" rather than as a discovery.

## 5. The Starter Playground: What It Proves

The starter playground is a runnable example, not the whole internship. **It is this repo.**

Main input:

```text
data/raw/content_refresh_anonymized.csv
```

The pipeline (run all of it with `python scripts/run_all.py`):

```text
01_prepare_features.py -> 02_baseline_score.py -> 03_train_model.py -> 04_evaluate_and_export.py -> 05_build_pdf_report.py
```

The starter target — the thing the starter model predicts — is:

```text
is_declining_label = trend_direction == "down"
```

This is simple on purpose. It shows the workflow end to end, but notice its weakness: it is a bucket calculated from the current window, not a future outcome. That makes it a beginner **proxy label** — a stand-in for the thing you really care about. Treat it that way, not as the ideal capstone target. A stronger capstone defines a future-looking outcome, like:

```text
features from prior 90 days -> decline or recovery over next 30 days
```

Exactly what the starter feature prep does:

- Input: `data/raw/content_refresh_anonymized.csv`.
- Required columns include `content_id`, `client_id`, `impressions_90d`, `sessions_90d`, `content_age_days`, and `trend_direction`.
- Rows are kept only when `impressions_90d > 0` and `content_age_days >= 90`.
- Rows are deduplicated by `content_id`.
- The data ships observable signals only; FlyRank's product decision flags were never included, so there is nothing to strip out. The label is `trend_direction == "down"`.

The starter model's features:

- Numeric features: search volume, competition, CPC, word/char count, logged 90d impressions/clicks/sessions/AI sessions, days with impressions/sessions, age, freshness, CTR, average position, engagement rate, scroll rate, and AI traffic percentage.
- Categorical features: competition level, content type, main intent, age tier, freshness tier, word-count tier, impression tier, and position tier.

The starter baseline score, exactly as coded:

```text
baseline_refresh_score =
  0.40 * visibility_score
+ 0.30 * freshness_risk_score
+ 0.25 * position_opportunity_score
+ 0.05 * depth_gap_score
```

Starter baseline reason codes (a **reason code** is a short tag that tells a human WHY a page got its score):

- `stale_visible_page`: `days_since_last_update >= 180` and `impressions_90d >= 500`
- `declining_with_demand`: `trend_direction == "down"` and `impressions_90d >= 100`
- `thin_visible_page`: `word_count > 0`, `word_count < 1200`, and `impressions_90d >= 250`
- `page_one_decay_risk`: `avg_position > 0`, `avg_position <= 10`, and `content_age_days >= 180`
- `low_ctr_visible_page`: `impressions_90d >= 500`, `0 < avg_position <= 20`, and `ctr < 0.5`
- `low_engagement_visible_page`: `sessions_90d >= 30` and `engagement_rate` or `scroll_rate` below 30

The starter's final score, exactly as coded:

```text
final_refresh_score =
  100 * (0.70 * best_model_probability + 0.30 * normalized_baseline_score)
```

Final starter reason codes:

- `model_decline_risk`: model probability >= 0.65
- `visible_model_opportunity`: model probability >= 0.50 and `impressions_90d >= 500`
- `ctr_review_candidate`: `impressions_90d >= 500`, average position 1-20, and `ctr < 0.5`
- `engagement_review_candidate`: `sessions_90d >= 30` and `engagement_rate` or `scroll_rate` below 30

The starter's high-confidence label also demands enough evidence: final score above the 80th percentile, `impressions_90d >= 500`, `sessions_90d >= 10`, and model probability >= 0.50.

Starter model results, verified from `outputs/model_results.json` and `outputs/model_report.md`:

| Method | ROC AUC | Average precision | Precision@50 |
|---|---:|---:|---:|
| baseline rules | 0.627 | 0.468 | 0.240 |
| logistic regression | 0.700 | 0.522 | 0.400 |
| decision tree | 0.742 | 0.575 | 0.540 |
| random forest | 0.750 | 0.618 | 0.740 |

What these numbers mean in plain words:

- **Precision@50** asks: of the top 50 pages the system says to review first, how many actually turned out positive by the chosen label?
- The baseline got about 12 of its top 50 right: `0.240 * 50`.
- The random forest got about 37 of its top 50 right: `0.740 * 50`.
- That is strong evidence that a learned ranking can beat a fixed rule — on this starter slice.

Keep the scope honest:

- This result comes from a 30,000-row anonymized starter slice.
- It used client-holdout validation (whole clients kept out of training, so the model is tested on clients it never saw).

In [28]:
nb03 = Path(
    "FlyRank-ML-W1/notebooks/03_working_with_the_full_release.ipynb"
)

print("Notebook 03 exists:", nb03.exists())

Notebook 03 exists: True

## 1. Question

*The research question and the decision it supports.*

## 2. Data

*Which release, which tables, date windows, what you excluded and why. Public-safe.*

## 3. Methodology

*Assumptions, features, label definition, baseline, validation design, leakage checks.*

## 4. Results (vs baseline)

*Model vs baseline on the same split. The honest table.*

## 5. Limitations

*What this work cannot claim.*

## 6. Ranked recommendations

*The action playbook output — the paper's recommendations section.*

## 7. Artifacts the paper embeds

*Generate/collect the charts and tables your deployed page will show.*

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.
- [ ] My deployed paper has **all 9 sections** — including the **Abstract** at the top and **Acknowledgments & data credit** (the https://flyrank.ai link) at the bottom.
- [ ] **ML-12 done in this notebook's closing cells:** 5-minute demo outline + a social-post cut + a 3-sentence employer-facing summary.